terms:
  - id: Audio
    term: Audio
  - id: Book
    term: Book
  - id: Dataset
    term: Dataset
  - id: Dissertation
    term: Dissertation
  - id: Image
    term: Image
  - id: Article
    term: Journal Article
  - id: Masters Thesis
    term: Masters Thesis
  - id: Part of Book
    term: Book Chapter
  - id: Poster
    term: Poster
  - id: Project
    term: Project
  - id: Report
    term: Report
  - id: Research Paper
    term: Research Paper
  - id: Video
    term: Video
  - id: Other
    term: Other