<%
def test_settings
  if url = ENV['DATABASE_URL']
    ActiveRecord::ConnectionAdapters::ConnectionSpecification::ConnectionUrlResolver.new(url).to_hash
  else
    {
      'host' => 'localhost',
      'port' => Docker::Stack.env.development? ? 5433 : 5434
    }
  end
end
%>

default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 5
  username: docker
  password: d0ck3r

development:
  <<: *default
  port: 5433
  database: docker_dev

test:
  <<: *default
  host: <%= test_settings['host'] %>
  port: <%= test_settings['port'] %>
  database: docker_test

production:
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: db/production.sqlite3
