active_job: {}
analytics: {}
arch:
  contact_email: digitalscholarship@northwestern.edu
  derivatives_path: /tmp/derivatives/
  fits_path: /usr/local/bin/fits
  google_analytics_id: UA-797260-32
  minter_state: /tmp/minter-state
  host: https://arch.library.northwestern.edu
aws:
  buckets: {}
  queues: {}
doi_credentials:
  default_shoulder: 'doi:10.5072/FK2'
  user: 'apitest'
  password: 'apitest'
  host: 'ezid.lib.purdue.edu'
  port: 443
  use_ssl: true
browse_everything:
  box:
    client_id:
    client_secret:
  file_system:
    home:
fedora: {}
solr:
  configset: arch
  configset_source_path: <%= File.join(Rails.root, 'solr', 'conf') %>
  collection_options:
    async:
    auto_add_replicas:
    collection:
      config_name: arch
    create_node_set:
    max_shards_per_node:
    num_shards: 1
    replication_factor:
    router:
      name:
      field:
    rule:
    shards:
    snitch:
