localstack:
  sqs: false
  port_offset: 100
active_job:
  queue_adapter: inline
aws:
  endpoint: https://localhost.localstack.cloud:4566
  buckets:
    archives: dev-archives
    dropbox: dev-dropbox
    proquest: dev-proquest
  queues:
    default: arch-queue
solrcloud: true
zookeeper:
  connection_str: "localhost:9983/configs"
proquest:
  dissertation_depositor: registered
