localstack:
  sqs: false
  port_offset: 100
active_job:
  queue_adapter: inline
aws:
  endpoint: http://localhost:9001
  buckets:
    archives: dev-archives
    dropbox: dev-dropbox
  queues:
    default: arch-queue
solrcloud: true
zookeeper:
  connection_str: "localhost:9983/configs"
