active_job:
  queue_adapter: active_elastic_job
arch:
  derivatives_path: /var/arch-derivatives
  ffmpeg_path: /usr/local/bin/ffmpeg
  fits_path: /usr/local/fits/fits.sh
  google_analytics_id: UA-797260-32
  minter_state: /var/arch-working/minter-state
  working_path: /var/arch-working
