localstack:
  sqs: false
  port_offset: 200
active_job:
  queue_adapter: inline
aws:
  endpoint: http://localhost:9002
  buckets:
    archives: test-archives
solrcloud: true
zookeeper:
  connection_str: "localhost:9985/configs"
