---
version: '3.4'
volumes:
  fedora:
  solr:
  db:
  localstack:
  minio:
services:
  fedora:
    image: nulib/fcrepo4
    volumes:
    - fedora:/data
    ports:
    - 8986:8080
  solr:
    image: solr:7.2-alpine
    ports:
    - 8985:8983
    - 9985:9983
    volumes:
    - solr:/opt/solr/server/solr/mycores
    command: solr -f -cloud
    healthcheck:
      test:
      - CMD
      - wget
      - "-O"
      - "/dev/null"
      - http://localhost:8983/solr/
      interval: 30s
      timeout: 5s
      retries: 3
  redis:
    image: redis:alpine
    ports:
    - 6381:6379
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 30s
      timeout: 5s
      retries: 3
  db:
    image: healthcheck/postgres:alpine
    volumes:
    - db:/data
    environment:
    - PGDATA=/data
    - POSTGRES_USER=docker
    - POSTGRES_PASSWORD=d0ck3r
    ports:
    - 5434:5432
  minio:
    image: minio/minio
    volumes:
      - minio:/data
    ports:
      - "9002:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command:
      - minio
      - server
      - /data
